### ISSUE TITLE
Scale

### ISSUE THREAD

**Issue by Theo-Farnole** [jjxtra/UnityLightsaber#1]
Hello ! 
Firstly, big thanks to you, it's the better lightsaber in Unity :)
But, when I try to scale down the lightsaber I've some issues:
Scale down the laserswordred root transform made nothing (0.2 every scale)
When I scale down the laserswordhilt transform everything works except LaserSwordBladeGlow that's keep the original scale. So I've try to modify BladeEnd to a shorter distance with BladeStart but it didn't fix the problem.

Thanks :)
And well play for this great asset ^^

**Comment by Blackcrow69** [comment]
I have the same issue and didn't find a fix yet

**Comment by jjxtra** [comment]
First person to PR a fix gets a big pat on the back!
